version: '3.8'

services:
  nginx:
    image: library/nginx:1-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - ${PWD}/dev/_nginx/default_location.conf:/etc/nginx/vhost.d/${DOMAIN_NAME}_location
      - ${PWD}/dev/_nginx/default.conf:/etc/nginx/vhost.d/${DOMAIN_NAME}
      - type: bind
        source: ${PWD}/App
        target: /var/www
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  dockergen:
    image: jwilder/docker-gen:0.7.3
    container_name: nginx-proxy-gen
    restart: unless-stopped
    depends_on:
      - nginx
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${PWD}/dev/_nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx
      - dockergen
    environment:
      DEFAULT_EMAIL: blckpearl.sheeper@gmail.com
      # Staging API, remove it after testing
      ACME_CA_URI: "https://acme-staging-v02.api.letsencrypt.org/directory"
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    name: nginx-proxy
    driver: bridge
